baseURL: 'https://eubnara.github.io/'
title: "EUB's second brain"
theme: 'PaperMod'
defaultContentLanguage: en
defaultContentLanguageInSubdir: false

params:
  author:
    name: eubnara
  comments: true
  env: production
  social: true
  mainSections:
    - computer-science
    - tools

languages:
  en:
    languageCode: en-us
    languageName: English
    contentDir: content/en
    weight: 1
    menu:
      main:
        - name: About
          url: about
          weight: 1
        - name: Archive
          url: archive
          weight: 2
        - name: Search
          url: search/
          weight: 3
        - identifier: categories
          name: categories
          url: /categories/
          weight: 4
        - identifier: tags
          name: tags
          url: /tags/
          weight: 5
  ko:
    languageCode: ko-kr
    languageName: 한국어
    contentDir: content/ko
    weight: 2
    menu:
      main:
        - name: About
          url: about
          weight: 1
        - name: Archive
          url: archive
          weight: 2
        - name: Search
          url: search/
          weight: 3
        - identifier: categories
          name: categories
          url: /categories/
          weight: 4
        - identifier: tags
          name: tags
          url: /tags/
          weight: 5

outputs:
    home:
        - HTML
        - RSS
        - JSON
