baseURL: 'https://eubnara.github.io/'
languageCode: 'en-us'
title: "EUB's second brain"
theme: 'PaperMod'

params:
  comments: true
  env: production
  social: false

menu:
  main:
    - name: About
      url: about
      weight: 5
    - name: Archive
      url: archives
      weight: 5
    - name: Search
      url: search/
      weight: 10
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
#     - identifier: example
#       name: example.org
#       url: https://example.org
#       weight: 30

outputs:
    home:
        - HTML
        - RSS
        - JSON
